### PR TITLE
Schematic updates

### PR DESCRIPTION
**Pull request by beetecservices**
I've put the basics in including pull-up resistors, reset / flash switches.

Possibly over complicating things with DP3T switch to select between USB power (programming / testing) and 3.7V or 3.2V battery (testing only). Not convinced I've got it right.

I've deliberately left resistor and capacitor values out for future discussion and used an AM1117 vreg just for convenience (placeholder).

Wires marked with PP_ prefix denote pogo pins.

Jumper between REST and GPIO16 for test purposes when deep sleep is needed - leave open for general use.

Comments welcome

### CODE REVIEW

**Comment by theopensourcerer** [comment]
I'm not convinced that a "programmer" board needs support for batteries at all? What is your thinking behind that?

**Comment by beetecservices** [comment]
When I forked your original repository it didn't fork the Wiki but I've
added to my Wiki to add design goals (if you can see it). I can't work out
how Wiki edits /merges work.

When you originally tagged me in the FB post about that pogo pin board I
replied saying it could be a generic programming / test rig (and you
agreed, I think).

In other words, post-programming it could be used for soak tests etc
without direct USB connection for debugging - basically unplug the USB
connector and put a battery in place and test the ESP software in the first
stage of being "in the wild" so to speak.

OK, 9 times out of 10 (or even 99 times out of 100) you might just want to
program an ESP module and briefly test it using USB power before taking it
off the rig and soldering it to whatever board, but with all the requisite
pull-up resistors, push switches and vreg circuitry / battery connectors
the board becomes a a replacement for a lot of breadboard development.

I was basically trying to find every eventuality (hah, unlikely) which is
why I also put a jumper between RST and GPIO16 in case deep sleep is /
isn't needed.

So that's basically it. Comments welcome.

**Comment by theopensourcerer** [comment]
OK - That makes sense - the scope is broader that I thought but that's fine - it's even more useful :-)

What that says to me then is that the schematic design needs to reflect this; things like a high efficiency, low drop-out, low quiescent current regulator etc.

The one I have been using is the MCP1700 which (I think) was the optimum spec I could find at the time: http://uk.rs-online.com/web/p/low-dropout-voltage-regulators/6989044/

**Comment by theopensourcerer** [comment]
Have added in the ESP and the MCP2221 chip and some pin labels but not done any further wiring,

There is one thing we need to "sync" is the Kicad libraries. When I open it it complains of unknown libraries for your switch and jumper. When you open this commit you'll probably get something similar ;-)

I think the next thing will be to start to build a footprint for the pogo pins which can then be associated with the ESP in the PCB layout.

**Comment by beetecservices** [comment]
Agreed about the regulator - I just needed a placeholder (i.e., anything
with 3 pins Vin/Vout/GND) to visualise that part of the circuit while I got
my head around the DP3T switch connections. I use the HT7333 (if you
remember a FB post I accidentally bought 100 of the things when I only
needed 10 - oops). It has a similar dropout voltage to the MCP1700 but a
slightly higher quiescent current.

I think the key thing here though is agreeing on a common package footprint
- it doesn't matter so much if the schematic shows an MCP1700 or HT7333 or
other similar regulator as the aim is ultimately the physical PCB. My
HT7333 regs are SOT-89 and fit the underside of those DIL adapter boards
(bloody fiddly) but if you're happier with SOT-23 then I'm fine with that.

Also agreed WRT Kicad libraries - what's the best approach? I'm guessing at
a directory within the project and a relative path in the library
preferences. The switch was my own creation from a DPDT stock item - the
jumper was an adaption of a 'broken' NO jumper (it had arcs between pins
1&2 as well as 2&3). I've noticed your VCC and GND power ports don't play
nice when I open your schematics (same with envmonitor) - I use the
standard ones from the 'power' library.

I've attached a screenshot of what I see although it'll be similar to what
you see. Where did you get the ESP8266 and Microchip libraries?

​

**Comment by theopensourcerer** [comment]
ESP Library: https://github.com/jdunmire/kicad-ESP8266
MCP Library: https://github.com/cpavlina/kicad-schlib

And this one has a lot of useful stuff in it: 
https://github.com/cpavlina/kicad-pcblib

I also use quite a few footprints from the "library of libraries":
https://github.com/monostable/kicad_footprints

**Comment by theopensourcerer** [comment]
You do need to be careful about using a generic component. Not all devices use the same pinout so when you connect it to a footprint you can end up in all sorts of grief. The MCP1700 has different pinouts between package types!

**Comment by theopensourcerer** [comment]
I thought I had used "standard" flags from the Power libraries?

**Comment by theopensourcerer** [comment]
No screenshot was in your earlier message... Maybe try adding it to this pull request discussion directly via the github web nterface?

**Comment by beetecservices** [comment]
Odd the screenshot image didn't come through - I thought this was basically
a gmail message thread? Still getting my head around github - an example
being when you added in the ESP and MCP2221 - I had to use the following
command line commands...

> git remote add upstream https://github.com/theopensourcerer/esp8266-programmer.git
> git fetch upstream
> git checkout master
> git merge upstream/master

...is that normal? I couldn't find a way to merge your changes through the
github web interface and only found out how to do the above after Googling
it.

OK, found the pull request by going to your master and have added the
screenshot. By putting my kicad_libs directory into the local project
directory I no longer have a problem with sw_dp3t or jumper_no_dual using a
relative path in the library settings. If you merge my kicad_libs directory
into the project and have the same relative path does that solve things? Is
it a good way to approach the library sync problem?

Thanks for the library links but where to put them (again re-iterating the
above)? You pointed me at the footprints library and I've got those already.

Agreed about generic parts - my main point was about the footprint / pin
connections IF they are interchangeable with other regulators. Example -
the SOT-89 package for MCP1700 is the same as the SOT-89 HT7333 WRT to
pinouts. The HT7333 is only available in TO-92 and SOT-89 packages however.
If you prefer SOT-23 I don't have a problem with that and my latest change
has an MCP1700 with SOT-23 footprint.

As for your power ports - for some reason they show up as 'rescue' items
when import your project changes. The VCC and GND labels overlap the
symbols. Not sure why that is.

**Pull request merged**
